Polkadot and Kusama validators
crypkit/coinaddrng pull request #3
Opened 2021-05-18 12:20 UTC by andrejkljucko

https://github.com/paritytech/substrate/wiki/External-Address-Format-(SS58)

2021-05-23 18:37 UTC, bibajz requested changes

2021-05-23 18:37 UTC, bibajz commented on coinaddrng/validation.py
> +        if address_decoded[0] & 0b0100_0000:
Vytahl bych tohle do separatni staticke metody, neco jako `_decode_address_format(address: bytes) -> SS58AddressFormat`.

`SS58AddressFormat` by byla separatni `attr.s` trida:

```
@attr.s(frozen=True, slots=True, auto_attribs=true)
class SS58AddressFormat:
    format_length: int
    format: int
```

+ Jsou to dobra jmena tech promennych?
+ Adresy zacinaji `0b1...` jsou rezervovane pro budouci pouziti, chceme je mit ted podporovat? Nebo vyhodime `UnsupportedError`? @galvanizze

2021-05-23 18:37 UTC, bibajz commented on coinaddrng/validation.py
> +        if len(address_decoded) in [3, 4, 6, 10]:
1. Celou tuhle `if/else` vytahnout do separatni staticke metody  `int -> int`
2. Porovnavat vuci `tuple`, ne `list`
3. Porovnani vuci jednoprvkovemu seznamu -> porovnat na rovnost.

2021-05-23 18:37 UTC, bibajz commented on coinaddrng/validation.py
> +        elif len(address_decoded) in [5, 7, 11, 34 + ss58_format_length, 35 + ss58_format_length]:
Pokud tam nejak potrebujes zakomponovat i `SS58AddressFormat`, informace, tak predchozi komentar modifikuj tak, aby ta metoda mela signaturu:

```
int -> SS58AddressFormat -> int
```

2021-05-23 18:37 UTC, bibajz commented on coinaddrng/validation.py
> +        checksum = blake2b(b'SS58PRE' + address_decoded[0:-checksum_length]).digest()
Malickost, ale `0` v tom slicu byt nemusi -> `address_decoded[:-checksum_length]`

2021-05-23 18:37 UTC, bibajz commented on tests/test_coinaddr.py
> +    ('kusama', 'ksm', b'GLdQ4D4wkeEJUX8DBT9HkpycFVYQZ3fmJyQ5ZgBRxZ4LD3S', '')
Abys pak nemel pri pridani dalsiho coinu vetsi diff, dej please na konec carku

2021-05-23 18:37 UTC, bibajz commented on coinaddrng/validation.py
> +        try:
Pridal bych k tomu `try/except` i `else` vetev, ktera se provede, pokud `try` blok projede dobre - tj.

```
else:
    return True
```

A u metody `validate` nevim, jak chceme byt defenzivni, tj. ten `return` na konci dat na `False`? @galvanizze ?

2021-05-26 12:08 UTC, andrejkljucko commented on coinaddrng/validation.py
> +        try:
`return False` na konci, po `else: return True` Idea oznacuje jako 'Unreachable code' :)

2021-06-04 19:47 UTC, bibajz commented on coinaddrng/validation.py
> +        try:
jj, mas pravdu, takze odstranit :)

2021-06-04 19:50 UTC, bibajz commented on coinaddrng/validation.py
> +        return SS58Address(ss58_format, format_length)
Tohle je malickost, ale jelikoz je to trida s 2 `int` atributy, takze bych to pro prehlednost vracel takhle:

```
return SS58Address(format=ss58_format, length=format_length)
```

2021-06-04 19:50 UTC, bibajz commented on coinaddrng/validation.py
> +    def _get_checksum_length(decoded_base58_len: int, ss58_address: SS58Address) -> int:
😍

2021-06-04 19:59 UTC, bibajz commented on coinaddrng/validation.py
> +        if ss58_address.format in [46, 47]:
Hm, kdyz o tom tak premyslim, co dat tenhle check do metody `_decode_ss58_address_format` ?

Tim padem by se tahle metoda uz nemusela starat o validitu *formatu* ale pouze o kodovani. Co rikas?

2021-07-16 11:51 UTC, merged